### PR TITLE
allowing storageclass to be used from config

### PR DESCRIPTION
**Pull request by svanellewee**
Good day! Sorry if I'm not following the correct process,  the contribution doc doesn't specify how to provide code changes. 

Myself and @nvulane have been testing this and found that the `storageClass` yaml configs are not being used. This PR is to allow for that. Other than that I just want to say this is a great db to work with!

Best regards,
Stephan and Nvulane.

### CODE REVIEW

**Comment by rkarthik007** [comment]
Hi @svanellewee 

Glad you like YugabyteDB! Please do let us know if you build a cool app on top or run a benchmark, would love to showcase your work!

Also, thanks to both you and Nvulane for your contribution! Could you both please add yourselves to the YugabyteDB contributor list: https://github.com/yugabyte/yugabyte-db/blob/master/CONTRIBUTORS.md

I have added a couple of folks as reviewers, they can help take this forward.

**Comment by svanellewee** [comment]
Will do @rkarthik007 ! Sorry for the long delay. Will add there. Also have added go mod changes and a removal of a silly line in the tests.

**Review by samkulkarni20 — APPROVED** [review]
LGTM

**Comment by ramkumarvs** [comment]
@svanellewee merged your changes. Thanks for the contribution!

**Comment by svanellewee** [comment]
Glad to help! Best of luck peeps!

**Pull request merged**
